### ISSUE TITLE
Panic: duplicate field `user`

### ISSUE THREAD

**Issue by wezm** [faebser/beautiful-wallpaper-every-day#1]
```
$ cargo run
XDG_PICTURES_DIR is "/home/wmoore"
wrote faulty json to "jsons/h6dT4DJ80n"
thread 'main' panicked at 'JSON PARSE ERROR: Error { kind: Json(ErrorImpl { code: Message("duplicate field `user`"), line: 1, column: 3128 }), url: None } 
 ""', src/main.rs:239:21
```

Problematic JSON:

```
{"id":"XQqOpGtnD6U","updated_at":"2018-03-23T12:24:56-04:00","username":"grakozy","name":"Greg Rakozy","first_name":"Greg","last_name":"Rakozy","twitter_username":"grakozy","portfolio_url":"http://grakozy.com","bio":"Like my photos? https://buymeacoff.ee/grakozy","location":"Salt Lake City, Utah","links":{"self":"https://api.unsplash.com/users/grakozy","html":"https://unsplash.com/@grakozy","photos":"https://api.unsplash.com/users/grakozy/photos","likes":"https://api.unsplash.com/users/grakozy/likes","portfolio":"https://api.unsplash.com/users/grakozy/portfolio","following":"https://api.unsplash.com/users/grakozy/following","followers":"https://api.unsplash.com/users/grakozy/followers"},"profile_image":{"small":"https://images.unsplash.com/profile-1495388545592-e4e376925c59?ixlib=rb-0.3.5&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=32&w=32&s=4a6479456ed968ba331e01668f231990","medium":"https://images.unsplash.com/profile-1495388545592-e4e376925c59?ixlib=rb-0.3.5&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=64&w=64&s=12ae79a24d842721d9a2e3969a24c1f8","large":"https://images.unsplash.com/profile-1495388545592-e4e376925c59?ixlib=rb-0.3.5&q=80&fm=jpg&crop=faces&cs=tinysrgb&fit=crop&h=128&w=128&s=913fbf5443cc4c00c436535f78b6d0aa","custom":"https://images.unsplash.com/profile-1495388545592-e4e376925c59?ixlib=rb-0.3.5&q=80&fm=jpg&crop=entropy&cs=tinysrgb&w=3840&fit=crop&s=2210724d2bfd4bc75d4851a26ff18cd9"},"total_collections":19,"instagram_username":"grakozy","total_likes":164,"total_photos":75},"current_user_collections":[],"slug":null,"location":{"title":"Hardware Ranch WMA, Hyrum, United States","name":"Hardware Ranch WMA","city":"Hyrum","country":"United States","position":{"latitude":41.6188037,"longitude":-111.5647165}},"exif":{"make":"Canon","model":"EOS 5D Mark II","exposure_time":"25","aperture":"2.8","focal_length":"14","iso":1600},"views":1949080,"downloads":14745}
```

rustc 1.24.0
FreeBSD 11.1-RELEASE-p6
GNOME 3.18.2

**Comment by faebser** [comment]
Thank you for your pointing out this issue. I will try to get around to fix it in the following days.

**Comment by davidde** [comment]
I'm having the same issue on Debian for every json. Any progress on fixing this?

**Comment by wezm** [comment]
I looked into this yesterday and the issue is the response from Unsplash contains the user field twice. 

It appears there is no way to control serde‘s behaviour in this scenario at the moment. There is an open issue to make it configurable: https://github.com/serde-rs/serde/issues/690

One option might be to report a bug to Unsplash.

**Comment by faebser** [comment]
I tried to find a github repo for the Unsplash API but it seems there isn't one. I pinged them on twitter to ask them.

In the meanwhile I will try to think about of a workaround.

**Comment by davidde** [comment]
That's too bad. Trying it out today, I got it to work a few times. Definitely a fun app when it works!

Small remark: when you don't yet have a jsons and backgrounds directory (in your workspace and Pictures directory respectively), there is a panic 'could not create ...: entity not found'.

**Comment by faebser** [comment]
Thank you for your kind words. I will get to implement the workaround after the easter weekend.

**Comment by wezm** [comment]
> I tried to find a github repo for the Unsplash API but it seems there isn't one.

It's not obviously linked but they are at: https://github.com/unsplash

**Comment by faebser** [comment]
I also found that organisation but it only contains repos for the official wrappers for the different languages and not for the API in general.

**Comment by faebser** [comment]
I just got a response from the API team:

> Hi Fabian. Thanks - we noticed this too and deployed a bugfix a few days ago, actually. Let me know if you have any other problems. 
> Aaron

I used the app for a few times without running into the bug but I'm gonna wait until you guys also manage to test it.

**Comment by davidde** [comment]
Yes, indeed! I already noticed I wasn't running into this anymore. I actually suspected something to have changed at unsplash's side. This confirms it. Great news.

I'm still running into another bug relating to strings, but I'll file another issue for that.
