### ISSUE TITLE
Panic: invalid type: null, expected a string

### ISSUE THREAD

**Issue by davidde** [faebser/beautiful-wallpaper-every-day#5]
```bash
$ cargo run
XDG_PICTURES_DIR is "/home/david/Pictures"
wrote faulty json to "jsons/wYL9CJnbcG"
thread 'main' panicked at 'JSON PARSE ERROR: Error { kind: Json(ErrorImpl { code: Message("invalid type: null, expected a string"), line: 1, column: 3450 }), url: None } 
 ""', src/main.rs:256:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
The json seems to be incomplete:
```json
"country":"United States","position":{"latitude":33.702679446692,"longitude":-117.010282939209}},"exif":{"make":"Sony","model":"ILCE-7RM2","exposure_time":"1/4000","aperture":"5.0","focal_length":"55","iso":100},"views":1537820,"downloads":16720}
```
Anyway, I'm thinking some `String` field in a struct should actually be `Option<String>`, I just can't tell which.
I'm kinda new to Serializing/Deserializing, and I'm wondering how to determine the struct type info. Is there some rule, or is it documented at unsplash?

**Comment by faebser** [comment]
Thanks for reporting this issue. I was also running into this from time to time. It is actually the reason why I tried to save the json from the request. 
Strangely it seems only to work up until where the error occurs. I might split this into another issue and ask for help on reddit.

You can find the documentation of the response for the random_photo endpoint here https://unsplash.com/documentation#get-a-random-photo

I went through a trial and error process where I would just try it out and change the structs according to the error messages. This one I did not manage to find.

**Comment by davidde** [comment]
OK, thanks for the info. I'll let you know if I happen to find something.
